language: php

matrix:
  include:
    - php: 7.3
      env: ANALYSIS='true'

  allow_failures:
    - php: nightly

before_script:
  - composer install -n

script:
  - if [[ "$ANALYSIS" != 'true' ]]; then vendor/bin/phpunit ; fi
  - if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)